CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    full_name varchar(255) NOT NULL,
    role varchar(255) NOT NULL,
    password_hash varchar(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'DEVELOPER'))
);

CREATE TABLE projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL,
    description text,
    owner_id bigint NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id),
    CONSTRAINT fk_projects_owner FOREIGN KEY (owner_id)
        REFERENCES users (id) ON DELETE NO ACTION
);

CREATE TABLE tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version bigint NOT NULL,
    title varchar(255) NOT NULL,
    description text,
    status varchar(255) NOT NULL,
    priority varchar(255) NOT NULL,
    type varchar(255) NOT NULL,
    project_id bigint NOT NULL,
    assignee_id bigint,
    due_date timestamp with time zone,
    is_overdue boolean NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_tickets PRIMARY KEY (id),
    CONSTRAINT fk_tickets_project FOREIGN KEY (project_id)
        REFERENCES projects (id) ON DELETE NO ACTION,
    CONSTRAINT fk_tickets_assignee FOREIGN KEY (assignee_id)
        REFERENCES users (id) ON DELETE NO ACTION,
    CONSTRAINT ck_tickets_status CHECK (status IN ('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE')),
    CONSTRAINT ck_tickets_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    CONSTRAINT ck_tickets_type CHECK (type IN ('BUG', 'FEATURE', 'TECHNICAL'))
);

CREATE TABLE ticket_dependencies (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    ticket_id bigint NOT NULL,
    blocked_by_ticket_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_ticket_dependencies PRIMARY KEY (id),
    CONSTRAINT uk_ticket_dependency UNIQUE (ticket_id, blocked_by_ticket_id),
    CONSTRAINT ck_ticket_dependencies_not_self CHECK (ticket_id <> blocked_by_ticket_id),
    CONSTRAINT fk_ticket_dependencies_ticket FOREIGN KEY (ticket_id)
        REFERENCES tickets (id) ON DELETE NO ACTION,
    CONSTRAINT fk_ticket_dependencies_blocker FOREIGN KEY (blocked_by_ticket_id)
        REFERENCES tickets (id) ON DELETE NO ACTION
);

CREATE TABLE comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    version bigint NOT NULL,
    ticket_id bigint NOT NULL,
    author_id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_comments_ticket FOREIGN KEY (ticket_id)
        REFERENCES tickets (id) ON DELETE NO ACTION,
    CONSTRAINT fk_comments_author FOREIGN KEY (author_id)
        REFERENCES users (id) ON DELETE NO ACTION
);

CREATE TABLE mentions (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    comment_id bigint NOT NULL,
    mentioned_user_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_mentions PRIMARY KEY (id),
    CONSTRAINT uk_comment_mentioned_user UNIQUE (comment_id, mentioned_user_id),
    CONSTRAINT fk_mentions_comment FOREIGN KEY (comment_id)
        REFERENCES comments (id) ON DELETE NO ACTION,
    CONSTRAINT fk_mentions_user FOREIGN KEY (mentioned_user_id)
        REFERENCES users (id) ON DELETE NO ACTION
);

CREATE TABLE attachments (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    ticket_id bigint NOT NULL,
    uploaded_by_user_id bigint,
    original_file_name varchar(255) NOT NULL,
    stored_file_name varchar(255) NOT NULL,
    content_type varchar(255) NOT NULL,
    size_bytes bigint NOT NULL,
    storage_path varchar(1024) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_attachments PRIMARY KEY (id),
    CONSTRAINT uk_attachments_stored_file_name UNIQUE (stored_file_name),
    CONSTRAINT fk_attachments_ticket FOREIGN KEY (ticket_id)
        REFERENCES tickets (id) ON DELETE NO ACTION,
    CONSTRAINT fk_attachments_uploader FOREIGN KEY (uploaded_by_user_id)
        REFERENCES users (id) ON DELETE NO ACTION
);

CREATE TABLE audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    action varchar(255) NOT NULL,
    actor_type varchar(255) NOT NULL,
    actor_user_id bigint,
    entity_type varchar(255) NOT NULL,
    entity_id bigint,
    details text,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id),
    CONSTRAINT ck_audit_logs_action CHECK (action IN (
        'CREATE', 'UPDATE', 'DELETE', 'RESTORE', 'LOGIN', 'LOGOUT',
        'AUTO_ASSIGN', 'AUTO_ESCALATE', 'ADD_DEPENDENCY', 'REMOVE_DEPENDENCY',
        'IMPORT', 'EXPORT'
    )),
    CONSTRAINT ck_audit_logs_actor_type CHECK (actor_type IN ('USER', 'SYSTEM')),
    CONSTRAINT ck_audit_logs_entity_type CHECK (entity_type IN (
        'USER', 'PROJECT', 'TICKET', 'COMMENT', 'ATTACHMENT',
        'DEPENDENCY', 'MENTION', 'AUTH'
    ))
);
